name: trading-bot-env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - xgboost
  - matplotlib
  - seaborn
  - plotly
  - jupyter-lab
  - pytables
  # not in conda:
  # - chart-studio
  # - python-binance